name: Verify workflows
on:
  push:
    branches:
      - main

jobs:
  verify:
    name: test
    runs-on: ubuntu-latest
    env:
      SKAFFOLD_PROFILE: "${{ github.action == 'just a test' && 'prod' || 'nonprod' }}"
    steps:
      - name: Test
        run: |
          echo "+++${SKAFFOLD_PROFILE}+++"
