name: Verify workflows
on:
  push:
    branches:
      - main

jobs:
  verify:
    name: test
    runs-on: ubuntu-latest
    env:
      PROD: "${{ 'foo' == 'foo' && 'prod' || 'nonprod' }}"
      NONPROD: "${{ 'foo' == 'bar' && 'prod' || 'nonprod' }}"
    steps:
      - name: Test
        if: 'startsWith(github.event.ref, ''refs/heads/'')'
        run: |
          echo "prod: _${PROD}_"
          echo "nonprod: _${NONPROD}_"
          echo "commit sha: ${GITHUB_SHA}"
